project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - hepatitis_b.qmd
    - tuberculosis.qmd
    - desnutricion.qmd
    - vih.qmd
    - anemia.qmd
    - hipertension.qmd
    - dengue.qmd
    - cambio_climatico.qmd
    - obesidad.qmd

website:
  title: "Sala situacional Salud intercultural e Investigación Social (2019-2024)"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Sala situacional: Salud Intercultural"
        menu: 
        - text: "Hepatitis B"
          href: hepatitis_b.qmd
        - text: "Tuberculosis"
          href: tuberculosis.qmd
        - text: "Desnutricion"
          href: desnutricion.qmd  
        - text: "VIH"
          href: vih.qmd
        - text: "Anemia"
          href: anemia.qmd
        - text: "Hipertensión"
          href: hipertension.qmd
        - text: "Dengue"
          href: dengue.qmd
        - text: "Cambio Climático"
          href: cambio_climatico.qmd
        - text: "Obesidad"
          href: obesidad.qmd
        

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    self-contained: true