project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - hepatitis_b.qmd
    - tuberculosis.qmd
    - desnutricion.qmd
    - vih.qmd
    - anemia.qmd
    - hipertension.qmd

website:
  title: "Sala situacional Salud intercultural e Investigación Social (2019-2024)"
  navbar:
    left:
      - href: index.qmd
        text: "Inicio"
      - href: hepatitis_b.qmd
        text: "Hepatitis B"
      - href: tuberculosis.qmd
        text: "Tuberculosis"
      - href: desnutricion.qmd
        text: "Desnutricion"
      - href: vih.qmd
        text: "VIH"
      - href: anemia.qmd
        text: "Anemia"
      - href: hipertension.qmd
        text: "Hipertensión"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    self-contained: true